### ISSUE TITLE
`#include <cpr/cpr.h>` would throw Error `No such file or directory` unless in `CMakeLists.txt`, `cpr` is changed to `cpr::cpr`

### ISSUE THREAD

**Issue by yihengwuKP** [snme/cs106L-assignment1#1]
First of all, thank you for sharing the resourses of CS106L! I am not Stanford student so this issue might just be my environment. I am sharing it so that other people might find it helpful.

**Sumary**
A include error would be thrown if I just set up the project and build it. I found that in my environment, I need to change the 
 line `target_link_libraries(main PRIVATE cpr)` to `target_link_libraries(main PRIVATE cpr::cpr)`  in `CMakeLists.txt` so that the cpr can be properly included.

**Version and Platform**
`gcc 11.1.0`
`cmake 3.21.3`
And I am using Manjaro as OS.

**Procedure to replicate**
1. `git clone https://github.com/snme/cs106L-assignment1.git`
2. `cd cs106L-assignment1`
3. `./setup.sh`
4. (I actually did a bit modification of main.cpp, but I believe this is not related to this issue) `./build_and_run.sh`

the Error message is: 
```bash
cs106L-assignment1/WikiRacer/wikiscraper.h:4:10: fatal error: cpr/cpr.h: No such file or directory
    4 | #include <cpr/cpr.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/main.dir/build.make:76: CMakeFiles/main.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
After I changed the line 12 in `CMakeLists.txt` `target_link_libraries(main PRIVATE cpr)` to `target_link_libraries(main PRIVATE cpr::cpr)`, the build runs successfully. I am not 100% sure why that is the case, but maybe it's just a version issue? This change is suggested by the installation message when I run `./vcpkg install cpr` separately.

**Comment by snme** [comment]
Thank you so much, @yihengwuKP ! This was an excellent suggestion, and your proposed fix worked! You're completely right-this did arise from a sort of version issue (the current `CMakeLists.txt` file worked as intended for the past few months, but it seems like a recent change has broken this). Great job debugging the issue! I also see that after running `./setup.sh`, the following text is written out:

    The package cpr provides CMake targets:

        find_package(cpr CONFIG REQUIRED)
        target_link_libraries(main PRIVATE cpr::cpr)

My apologies! I should have noticed this the first time around, but thank you so much again for pointing it out! 

I'd love to keep in touch, @yihengwuKP, especially because I also do polymer/MD research at Stanford, and would love to chat! :D My email is sath@stanford.edu. I'd love to schedule a zoom call just to get to know you, if you have some free time!

**Comment by snme** [comment]
^also updated this in the assignment 2 repository, lined above

**Comment by yihengwuKP** [comment]
Hi Sathya, that sounds great! I am glad that you also do polymer/MD research! I'll send you an email for the zoom call

**Comment by yihengwuKP** [comment]
just to make sure, can you receive my email about the zoom or it's in spam? I've tried to send from uchicago email and gmail @snme
